---
- name: Run yanghui_server container using latest image
  hosts: server
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: yanghui_server
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            yanghui_server:
              image: highperformancecomputing/cdcf:latest
              container_name: yanghui_server
              environment:
                HOST: "{{ server }}"
                ROLE: root
                SEEDS: "{{ server }}:4445"
                LOG_COMMANDS: --log_file=/tmp/log/yanghui_root_v2.log --log_level=debug --log_file_size=65535
                APP: /bin/yanghui_cluster_root_v2
                APP_ARGS: "-r --root_host={{ server }} --root_port=56600 --worker_port=56601 --threads_proportion=2 --log_file=/tmp/log/actorsystem_yanghui_root_v2.log --log_level=debug --log_file_size=65535"
              network_mode: host
              ulimits:
                core: -1
              security_opt:
                - seccomp=unconfined
              volumes:
                - /tmp:/tmp
    - assert:
        that:
          - "yanghui_server.yanghui_server.state.running"
- name: Run yanghui_worker container using latest image
  hosts: worker
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: yanghui_worker
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            yanghui_worker:
              image: highperformancecomputing/cdcf:latest
              container_name: yanghui_worker
              environment:
                HOST: "{{ worker }}"
                ROLE: worker
                SEEDS: "{{ server }}:4445"
                LOG_COMMANDS: --log_file=/tmp/log/yanghui_worker1_v2.log --log_level=debug --log_file_size=65535
                APP: /bin/yanghui_cluster_root_v2
                APP_ARGS: "--root_host={{ server }} --root_port=56600 --worker_port=56601 --threads_proportion=2 --log_file=/tmp/log/actorsystem_yanghui_worker1_v2.log --log_level=debug --log_file_size=65535"
              network_mode: host
              cpus: "{{ cpus }}"
              volumes:
                - /tmp/log:/tmp/log
    - assert:
        that:
          - "yanghui_worker.yanghui_worker.state.running"
- name: Run yanghui_client container using latest image
  hosts: client
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: yanghui_client
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            yanghui_client:
              image: highperformancecomputing/cdcf:latest
              container_name: yanghui_client
              environment:
                HOST: "{{ client }}"
                ROLE: client
                SEEDS: "{{ server }}:4445"
                LOG_COMMANDS: --log_file=/tmp/log/yanghui_client.log --log_level=debug --log_file_size=65535
                APP: ""
                APP_ARGS: "--role=client --root_host={{ server }} -l 1 --root_port=56600 --worker_port=56601 --threads_proportion=2 --log_file=/tmp/log/actorsystem_yanghui_client.log --log_level=debug --log_file_size=65535"
              network_mode: host
              volumes:
                - /tmp/log:/tmp/log
    - assert:
        that:
          - "yanghui_client.yanghui_client.state.running"
