name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
    - name: Install conan && conan package tools
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools
    - uses: actions/checkout@v1
    - name: conan
      run: |
        conan remote add inexorgame "https://api.bintray.com/conan/inexorgame/inexor-conan"
        conan install . -s compiler.libcxx=libstdc++11 --build missing
    - name: cmake
      run: |
        cmake . -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
        cmake --build .
        ctest --output-on-failure
